### ISSUE TITLE
ImportError: No module named septo3d

### ISSUE THREAD

**Issue by sujithgunturu** [openalea-incubator/astk#13]
`from alinea.astk.Weather import sample_weather`
`seq, weather = sample_weather()`

`ImportError                               Traceback (most recent call last)
<ipython-input-29-4f863d9a411e> in <module>()
----> 1 seq, weather = sample_weather()

c:\users\personal\.conda\envs\openaleatotestadel\lib\site-packages\alinea.astk-0.3.0-py2.7.egg\alinea\astk\Weather.pyc in sample_weather(periods)
    257     """
    258     from openalea.deploy.shared_data import shared_data
--> 259     import alinea.septo3d
    260
    261     meteo_path = shared_data(alinea.septo3d, 'meteo00-01.txt')

ImportError: No module named septo3d`

**Comment by sujithgunturu** [comment]
Sometimes

`from pvlib.irradiance import get_extra_radiation`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name get_extra_radiation

**Comment by pradal** [comment]
I have the same. I investigate.
What is your version of pvlib? 0.5.2?

```import pvlib; print pvlib.version.__version__```

**Comment by sujithgunturu** [comment]
> I have the same. I investigate.
> What is your version of pvlib? 0.5.2?
> 
> `import pvlib; print pvlib.version.__version__`

>>> import pvlib; print pvlib.version.__version__
0.5.2
yes it is 0.5.2
